### ISSUE TITLE
Train from a pretrained model

### ISSUE THREAD

**Issue by miguelwon** [epfml/sent2vec#102]
Is it possible to train a new model starting from pre-defined word embedding vectors?

**Comment by guptaprkhr** [comment]
Hello, 
Yes. 
You can use "--sent2vecFromDict" argument to train from a pre-trained model. 
See https://github.com/epfml/sent2vec/blob/74ae0313aca7145df6baa3e61f6a6314fdc72b7a/src/fasttext.cc#L1040
