### ISSUE TITLE
Misleading sent2vec package on PyPI

### ISSUE THREAD

**Issue by Stannislav** [epfml/sent2vec#117]
There's a packagen [on PyPI](https://pypi.org/project/sent2vec/) called `sent2vec` that's linked to a [totally different repository](https://github.com/pdrm83/sent2vec).

Whoever does
```bash
$ pip install sent2vec
```
will get that wrong package.

One diagnostic of the wrong installation is the following error
```python
>>> sent2vec.Sent2vecModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sent2vec' has no attribute 'Sent2vecModel'
```

I saw that there are several issues out there reporting a similar problem (#42, #43 , #61, https://github.com/ncbi-nlp/BioSentVec/issues/16) and it's possible that some of them are due to the wrong package on PyPI.

Which steps could be taken?
- Warn abou this in the README file
- Talk to the maintainer of the other `sent2vec` package?
- Be prepared to answer other issues with the same problem.

**Comment by guptaprkhr** [comment]
Thank you for bringing this to notice. We have put a warning in the readme. We will try to resolve the issue on PyPI as well.
- Prakhar
