### ISSUE TITLE
how to install sent2vec in google colab or local server

### ISSUE THREAD

**Issue by BoonthichaSaejia** [epfml/sent2vec#118]
i am really new but want to try your library. Would you mind explain how to install this library step by step

**Comment by mpagli** [comment]
It might be difficult on colab, as you need to download the models which are quite large. But it should work on any linux server. 

Ton install the lib:
- clone the repo
- in a terminal go in the repo and run the `make` command
- install the python wrapper with `pip install .`

something like:

```bash 
git clone https://github.com/epfml/sent2vec.git
cd sent2vec
make
pip install . 
```
