### ISSUE TITLE
call is not working even with fasttext provided by this repository

### ISSUE THREAD

**Issue by vsbiradar** [epfml/sent2vec#15]
the call is giving ouput as 2, so its not running properly. when I checked the output of call using check_output method in subprocess it says the command returned non-zero exit. I am attaching the trace of the error.

CalledProcessError                        Traceback (most recent call last)
<ipython-input-55-e7268dd4bc0f> in <module>()
      1 sentences = ['Once upon a time.', 'And now for something completely different.']
      2 
----> 3 my_embeddings = get_sentence_embeddings(sentences, 'unigrams', 'wiki')
      4 print(my_embeddings.shape)

<ipython-input-54-30cc29706dca> in get_sentence_embeddings(sentences, ngram, model)
     67 
     68         if ngram == 'unigrams':
---> 69             wiki_embeddings = get_embeddings_for_preprocessed_sentences(tokenized_sentences_SNLP,                                      MODEL_WIKI_UNIGRAMS, FASTTEXT_EXEC_PATH)
     70             print "came to if"
     71         else:

<ipython-input-54-30cc29706dca> in get_embeddings_for_preprocessed_sentences(sentences, model_path, fasttext_exec_path)
     13           model_path + ' < '+
     14           test_path + ' > ' +
---> 15           embeddings_path, shell=True)
     16     embeddings = read_embeddings(embeddings_path)
     17     os.remove(test_path)

/home/vaijenath/anaconda2/lib/python2.7/subprocess.pyc in check_output(*popenargs, **kwargs)
    571         if cmd is None:
    572             cmd = popenargs[0]
--> 573         raise CalledProcessError(retcode, cmd, output=output)
    574     return output
    575 

CalledProcessError: Command '/home/vaijenath/Vaiju/Project/all code and data/My Code/sent2vec-master/src/fasttext print-sentence-vectors /home/vaijenath/Vaiju/Project/all code and data/My Code/TrainedModels/wiki_unigrams.bin < /home/vaijenath/Vaiju/Project/all code and data/My Code/sent2vec-master/1511975965.08_fasttext.test.txt > /home/vaijenath/Vaiju/Project/all code and data/My Code/sent2vec-master/1511975965.08_fasttext.embeddings.txt' returned non-zero exit status 2

where,    /home/vaijenath/Vaiju/Project/all code and data/My Code/sent2vec-master/ is my path where i am running this file.

**Comment by martinjaggi** [comment]
please can you first check if you get a similar issue if you try the same dataset with [fasttext](https://github.com/facebookresearch/fastText) instead of sent2vec? this would be important to know since your issue is about a code part with is mostly shared with fasttext.

**Comment by vsbiradar** [comment]
Yes. I tried  that. And it is working fine. When i run sent2vec using facebook's fasttext it is running from terminal but giving error OSError: [Errno 2] No such file or directory while it running from python notebook. If I use fasttext.cc given in this git repository i am getting above error.

**Comment by vsbiradar** [comment]
from subprocess import check_output
from subprocess import call
a = call('./fasttext print-sentence-vectors ~/Vaiju/Project/all code and data/My Code/TrainedModels/wiki_unigrams.bin < 1fasttext.test.txt')

The error is 

OSError                                   Traceback (most recent call last)
<ipython-input-2-72e01577b26b> in <module>()
      1 from subprocess import check_output
      2 from subprocess import call
----> 3 a = call('./fasttext print-sentence-vectors ~/Vaiju/Project/all code and data/My Code/TrainedModels/wiki_unigrams.bin < 1fasttext.test.txt')
      4 
      5 

/home/vaijenath/anaconda2/lib/python2.7/subprocess.pyc in call(*popenargs, **kwargs)
    520     retcode = call(["ls", "-l"])
    521     """
--> 522     return Popen(*popenargs, **kwargs).wait()
    523 
    524 

/home/vaijenath/anaconda2/lib/python2.7/subprocess.pyc in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags)
    708                                 p2cread, p2cwrite,
    709                                 c2pread, c2pwrite,
--> 710                                 errread, errwrite)
    711         except Exception:
    712             # Preserve original exception in case os.close raises.

/home/vaijenath/anaconda2/lib/python2.7/subprocess.pyc in _execute_child(self, args, executable, preexec_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell, to_close, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
   1333                         raise
   1334                 child_exception = pickle.loads(data)
-> 1335                 raise child_exception
   1336 
   1337 

OSError: [Errno 2] No such file or directory
But this works fine from terminal.

**Comment by martinjaggi** [comment]
so if it runs fine from terminal why does your python not call the same function? you never actually shared your python code so it's hard for me to see what you are trying

**Comment by vsbiradar** [comment]
for the code:
from subprocess import check_output
from subprocess import call
print check_output('./fasttext supervised -input traindata.ft.txt -output model_kaggle -label label')

The error  I am getting is
OSError                                   Traceback (most recent call last)
<ipython-input-15-41c935b76cda> in <module>()
      1 from subprocess import check_output
      2 from subprocess import call
----> 3 print check_output('./fasttext supervised -input traindata.ft.txt -output model_kaggle -label  __label__')
      4 
      5 #a = check_output('./fasttext print-sentence-vectors ~/Vaiju/Project/all code and data/My Code/TrainedModels/wiki_unigrams.bin < 1fasttext.test.txt')

/home/vaijenath/anaconda2/lib/python2.7/subprocess.pyc in check_output(*popenargs, **kwargs)
    564     if 'stdout' in kwargs:
    565         raise ValueError('stdout argument not allowed, it will be overridden.')
--> 566     process = Popen(stdout=PIPE, *popenargs, **kwargs)
    567     output, unused_err = process.communicate()
    568     retcode = process.poll()

/home/vaijenath/anaconda2/lib/python2.7/subprocess.pyc in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags)
    708                                 p2cread, p2cwrite,
    709                                 c2pread, c2pwrite,
--> 710                                 errread, errwrite)
    711         except Exception:
    712             # Preserve original exception in case os.close raises.

/home/vaijenath/anaconda2/lib/python2.7/subprocess.pyc in _execute_child(self, args, executable, preexec_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell, to_close, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
   1333                         raise
   1334                 child_exception = pickle.loads(data)
-> 1335                 raise child_exception
   1336 
   1337 

OSError: [Errno 2] No such file or directory

but the command in check_output is working well on terminal.

**Comment by mpagli** [comment]
Hi vsbiradar, 

That's just a wild guess, but could you try removing spaces from you paths ? 

`/home/vaijenath/Vaiju/Project/all code and data/My Code/sent2vec-master/` would become `/home/vaijenath/Vaiju/Project/all_code_and_data/My_Code/sent2vec-master/`
