### ISSUE TITLE
 ImportError: No module named Cython.Build

### ISSUE THREAD

**Issue by lokesh005** [epfml/sent2vec#18]
I have cython already in my system but when I execute `sudo pip install .` command. Following error pops up    

    `The directory '/home/lokesh/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/home/lokesh/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Processing /home/lokesh/Desktop/Unsupervised_KeYEx/sent2vec/src
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-8ApShB-build/setup.py", line 2, in <module>
            from Cython.Build import cythonize
        ImportError: No module named Cython.Build
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-8ApShB-build/
`

My python version is 2.7

**Comment by mpagli** [comment]
I did not tested the wrapper with python 2.7, only with python 3.6. I will try to find some time to investigate this.

**Comment by lokesh005** [comment]
Thanks @mpagli, the problem is resolved. I uninstalled `scikit-learn` package and installed it again and now it was working fine.
