### ISSUE TITLE
Issues with code and wikipedia model files

### ISSUE THREAD

**Issue by hseelawi** [epfml/sent2vec#2]
I want to bring to your attention that 'print-vectors' is not a valid command in fasttext anymore (there is either 'print-word-vectors' or 'print-sentence-vectors'. Additionally, please notice that the wikipedia model files sent2vec_wiki_bigrams and sent2vec_wiki_unigrams get 'Model file has wrong file format!' messages from fasttext (I haven't tested the twitter files).

**Comment by guptaprkhr** [comment]
Hi,
Thank you for bringing this to our notice. The thing is that original fasttext library has been updated without any backward compatibility. We are working to update our sent2vec model accordingly and there will be an update in a few days. 
However, to use these models you can use the fasttext file in this sent2vec git repo and things will be fine. Just make sure that you are using the ./fasttext file from this repo.

**Comment by hseelawi** [comment]
Alright, thank you very much for your kind and fast reply.
