### ISSUE TITLE
How about consider subword in sen2vec

### ISSUE THREAD

**Issue by wugh** [epfml/sent2vec#23]
The sen2vec is more like the supervise fasttex. have you tried add subword info for each word,
so the model can deal with oov.

**Comment by martinjaggi** [comment]
indeed, subwords could potentially also help for our unsupervised setting. as our code is very close to the fasttext one, it should be possible to add that feature. if someone would contribute it would be nice!

**Comment by wugh** [comment]
@martinjaggi I try to add sub word information when we get sentence level context, but the performance on my dataset is decrease a little bit. (The train and test corpus is Chinese)

no sub word  version performance
```
pearson = 0.3519, spearman = 0.3645, auc = 0.7104
```

sub word version performance 
```
pearson = 0.3464, spearman = 0.3486, auc = 0.7013
```

I'm think whether is it good to add sub word information. When the context get long, the sub word information will be quite noise, because I put all sub word and word in same level as a bow. And May be  Chinese does not contain very much sub word information. Do you have some idea about this?

**Comment by wugh** [comment]
@martinjaggi I try to add sub word information when we get sentence level context, but the performance on my dataset is decrease a little bit. (The train and test corpus is Chinese)

no sub word  version performance
```
pearson = 0.3519, spearman = 0.3645, auc = 0.7104
```

sub word version performance 
```
pearson = 0.3464, spearman = 0.3486, auc = 0.7013
```

I'm think whether is it good to add sub word information. When the context get long, the sub word information will be quite noise, because I put all sub word and word in same level as a bow. And May be  Chinese does not contain very much sub word information. Do you have some idea about this?

**Comment by wugh** [comment]
Thank you @mpagli .
Actually you are right, my implementation give every sub-component of the sentence level bow same result. But I see the CBOW of Fasttext is doing this too, i.e. share same weight for every component of the context.
