### ISSUE TITLE
Install instructions for python

### ISSUE THREAD

**Issue by SamuelLarkin** [epfml/sent2vec#28]
Hi,
  I want to install the python version of sent2vec.  Here are the provided instructions from your site:
```
python setup.py build_ext
sudo pip install .
```
But there is no setup.py file in the repository.  Should I be copying the fastText's setup.py in order to install sent2vec's python version?

**Comment by mpagli** [comment]
The `setup.py` file is in the `src` folder. You should run the commands from the `src` folder.
