### ISSUE TITLE
No similar sentences returned when using fasttext to search for nearest neighbours

### ISSUE THREAD

**Issue by Crista23** [epfml/sent2vec#29]
When using fasttext search for the nearest neighbours, there are cases when no similar sentence is retrieved even though an identical sentence with the one I am feeding as input already exists in the collection of sentences I am searching for. What is the explanation for this, in which scenarios does this occur? Is this a limitation of the model or a bug?

**Comment by guptaprkhr** [comment]
Can you tell me the training details? I was unable to reproduce the bug locally.
