### ISSUE TITLE
Learned Embeddings

### ISSUE THREAD

**Issue by EliHei** [epfml/sent2vec#30]
Hi,

How can I extract the embedding vectors after using `./fasttext sent2vec...` on a training set of sentences?

**Comment by mpagli** [comment]
Hi @EliHei,

By embedding vectors you mean n-gram embedding vectors? You can extract the unigram embeddings by asking sentence embeddings for each word of your vocabulary. For bigram embeddings it is a bit more tricky, each bigram is mapped to an embedding through some hashing function and there is no functionality to give a list of ngrams and get the associated embeddings.

I hope this is answering your question :) ?

**Comment by EliHei** [comment]
@mpagli So much thanks for your discussion.

By embedding I mean the sentence representation in h-dimentional space. I think in fastText such embeddings will be stored in a .vec file. I am looking for such file. (An n*h matrix where n is the number of training sentences and h is the dimension of representation space.)

**Comment by EliHei** [comment]
Got it! Thanks.

**Comment by patrickfrank1** [comment]
Hi, 

Does that mean it is impossible to manually compose sentence embeddings by averaging all n-grams it is composed of?

I tried it here, but it does not seem to work?!
[https://colab.research.google.com/drive/1NAxHZShWSj9X4YYXSfkpCOrE1C6hOIMe](https://colab.research.google.com/drive/1NAxHZShWSj9X4YYXSfkpCOrE1C6hOIMe)


Best, Patrick

**Comment by mpagli** [comment]
> Does that mean it is impossible to manually compose sentence embeddings by averaging all n-grams it is composed of?

You would need to apply the same hashing function to locate the ngram embeddings in the matrix. 

Asking for the embedding of "i-like" will give you the unigram embedding of "i-like". If you ask for the embedding of "i like" then you'll get the average between the unigram emb of "i" the unigram emb of "like" and the bigram emb of "i like". I guess you could retrieve the bigram embedding of "i like" by subtracting the unigram embeddings from the sent2vec embedding.

**Comment by patrickfrank1** [comment]
@mpagli thanks for the explaination.
I tried to reconstruct the bigrams in the way you suggested above (see same colab notebook from above). It works as far as I can tell.
Best, Patrick
