### ISSUE TITLE
How to save model on each epoch? 

### ISSUE THREAD

**Issue by daridar** [epfml/sent2vec#39]
Is it possible to save model during training (like using callbacks on each epoch finish)? 

1. And how to enable logging in your model?
With verbosity not a lot of information available. 
2. And is it possible to train model with 2 or more documents as input at once? 

Also:
3. Is it possible to call building a new model from python? 
Or just with command line? 

Thanks in advance.

**Comment by mpagli** [comment]
1- Only basic information is available through logging. But what would you like to see logged? 
2- You need to push the two documents in one file, a simple `cat doc1 doc2 > merge_docs` would do. 
3- no :(, only the commandline is available to start training

**Comment by daridar** [comment]
1 . ![image](https://user-images.githubusercontent.com/33403645/43077379-058e0838-8e90-11e8-9e9b-0a307b3445fe.png)

That's all the information I got from the training phase. 
I don't really know if it's training right now, or stucked . 

2. Thank you, I'll use this tip!
3. Thanks. Maybe in the next release?)

**Comment by daridar** [comment]
And again:

> Is it possible to save model during training (like using callbacks on each epoch finish)?
 ))

**Comment by daridar** [comment]
Or continue training model on the same corpus? For example, I trained my model during 2 epochs and want to continue training. Is it possible?

**Comment by guptaprkhr** [comment]
Hi @daridar ,
we will be adding support for checkpoints soon.
