### ISSUE TITLE
How could I search better parameters? (or add getLoss() to python interface)

### ISSUE THREAD

**Issue by shogo-osawa** [epfml/sent2vec#41]
I'm trying to train my unsupervised sent2vec model with Japanese text. Though the paper shows good parameters for English wikipedia, tweets, etc, they might not be good for my Japanese corpus. To search for good parameters, I'd like to know the loss of a trained model.

I guess [getLoss()](https://github.com/epfml/sent2vec/blob/e3ec994dcee8682bc6becb61943c606ed5ab7b6e/src/model.h#L100) method might be for this. But I could not find the python equivalent. Is it possible to add this method to python interface?

Thank you.

**Comment by martinjaggi** [comment]
for japanese the best parameters are likely going to be very different indeed.
optimizing for a good loss value is not enough, but it would be necessary to evaluate on a test task, such as sentence similarity or word similarity in japanese. for this you'd have to export the embeddings anyway, so i'm not sure just calling getLoss() would help. if you find some suitable dataset please let us know, we'd be interested to hear!
