### ISSUE TITLE
Training does not complete but program exits

### ISSUE THREAD

**Issue by Ashboy64** [epfml/sent2vec#44]
Hello, I'm using the library on windows and am trying to generate embeddings on my own data. Upon running:

`fasttext.exe sent2vec -input C:\....\fasttext_formatted_data.txt -output sent2vec_model`

the following is shown:

```
Read 2M words
Number of words:  10117
Number of labels: 0
Progress: 0.0%  words/sec/thread: 2016  lr: 0.199933  loss: 7.489615  eta: 0h13m
```
After a moment, the program exits and the progress jumps to 1%. No model is saved after the program exits. How can I get sentence embeddings on my data?

**Comment by guptaprkhr** [comment]
Hi,
I don't think sent2vec is compatible with Windows. Try training on an unix based system.
