### ISSUE TITLE
Using fastText to compute the sentence vectors

### ISSUE THREAD

**Issue by ninikolov** [epfml/sent2vec#47]
Hi, 

Am I correct in thinking there is no difference between using sent2vec's python interface, and loading the sent2vec model directly into fastText to access the word vectors? E.g. using your Wikipedia unigram model I get: 

```
>>> sent2vec_model.embed_sentence("hello world")

array([-8.04620683e-01,  8.93464625e-01, -3.09190452e-02, -1.37415811e-01,
       -3.63196850e-01,  2.66210616e-01, -7.63243794e-01,  8.93934608e-01,
```

and with fastText: 

```
>>> fasttext_model = fastText.load_model("wiki_unigrams.bin")
>>> (fasttext_model.get_word_vector("hello") + fasttext_model.get_word_vector("world"))/2

array([-8.04620683e-01,  8.93464625e-01, -3.09190452e-02, -1.37415811e-01,
       -3.63196850e-01,  2.66210616e-01, -7.63243794e-01,  8.93934608e-01,
```

Thanks for the info.

**Comment by martinjaggi** [comment]
this is true if you only care about unigrams (word vectors), if you load our provided models as opposed to pretrained fasttext. the sent2vec models however also add bi-gram and tri-gram vectors, which you would not get by this approach.

**Comment by mpagli** [comment]
Which OS are you using?

**Comment by welcomebyvenkat** [comment]
> Which OS are you using?

Its RHEL.

**Comment by mpagli** [comment]
`embed_sentence` shouldn't take two hours. Maybe try to use `embed_sentences` instead of `embed_sentence`. Could it be your gcc version?
