### ISSUE TITLE
Please put pre-trained models on S3

### ISSUE THREAD

**Issue by turian** [epfml/sent2vec#49]
On EC2, it is exceedingly difficult to download Google Drive files. Could you please mirror or move the pre-trained models to S3

**Comment by turian** [comment]
This script seemed to work for me: [gdown.pl]{https://github.com/circulosmeos/gdown.pl}
But it took a pit of fiddling to find this solution.
What about a common S3 block

**Comment by mpagli** [comment]
Hi, Thanks for finding a workaround. I can't do it now but I'll investigate the S3 solution over the weekend.

**Comment by turian** [comment]
ping

**Comment by mpagli** [comment]
Try with those:

https://s3.amazonaws.com/epfml-sent2vec-models/wiki_bigrams.bin
https://s3.amazonaws.com/epfml-sent2vec-models/wiki_unigrams.bin

https://s3.amazonaws.com/epfml-sent2vec-models/twitter_bigrams.bin
https://s3.amazonaws.com/epfml-sent2vec-models/twitter_unigrams.bin

Let me know if you encounter any issue
