### ISSUE TITLE
Extracting parameters from model 

### ISSUE THREAD

**Issue by daridar** [epfml/sent2vec#50]
How can we extract the parameters with whom our model was trained?  

For example, I have a model file and I want to know, what's vector size here, min count, how many epochs were performed and something like that?  

Thank you!

**Comment by martinjaggi** [comment]
how to extract the word embeddings from a trained model is described here: https://github.com/epfml/sent2vec/#unigram-embeddings

we don't store the statistics on training such as number of epochs etc, but for the available pre-trained models we provide them in the paper
