### ISSUE TITLE
French pre-trained model

### ISSUE THREAD

**Issue by xiaohai12** [epfml/sent2vec#57]
Hi, I am a master student of EPFL and I am interested in French pre-trained models.
Do you already have some pre-trained model for French?
Thanks.

**Comment by mpagli** [comment]
We do not have a pre-trained French model. But drop an email to me and Prakhar (https://people.epfl.ch/), we have a large french dataset and we might be able to work something out.

**Comment by Wissben** [comment]
@mpagli Hello, is there any news concerning the French pretrained model yet ? thanks
