### ISSUE TITLE
Error run get_sentence_embeddings_from_pre-trained_models

### ISSUE THREAD

**Issue by nguyenxuanhoi2903** [epfml/sent2vec#65]
I run get_sentence_embeddings_from_pre-trained_models but result my_embeddings.shape is (0,)

**Comment by mpagli** [comment]
Did you try using the python wrapper instead?

**Comment by nguyenxuanhoi2903** [comment]
<img width="1147" alt="Screen Shot 2019-04-01 at 7 36 58 PM" src="https://user-images.githubusercontent.com/33613154/55328216-08cdd900-54b6-11e9-8854-8889042237d6.png">
I used to 16GB (700dim, trained on english wikipedia) but it not working. Can you help me ??

**Comment by mpagli** [comment]
Did you link the models correctly? 

```python
MODEL_WIKI_UNIGRAMS = os.path.abspath("./sent2vec_wiki_unigrams")
MODEL_WIKI_BIGRAMS = os.path.abspath("./sent2vec_wiki_bigrams")
```

**Comment by nguyenxuanhoi2903** [comment]
<img width="1171" alt="Screen Shot 2019-04-05 at 2 24 54 PM" src="https://user-images.githubusercontent.com/33613154/55611073-a6732200-57ae-11e9-9536-309903a74753.png">
I checked it and it was completely correct. (wiki_bigrams 16gb).

**Comment by mpagli** [comment]
Did you try to use the Python wrapper? I'll try to see this weekend if I can fix the notebook, but the Cython wrapper should be the default solution unless you're on Windows or Mac

**Comment by kionfukuda** [comment]
I had a similar error. The embeddings created was empty.

Traceback (most recent call last):
  File "main.py", line 145, in <module>
    my_embeddings = get_sentence_embeddings(sentences, ngram='bigrams', model='twitter')
  File "main.py", line 134, in get_sentence_embeddings
    MODEL_TWITTER_BIGRAMS, FASTTEXT_EXEC_PATH)
  File "main.py", line 73, in get_embeddings_for_preprocessed_sentences
    assert(len(sentences) == len(embeddings))
AssertionError

**Comment by guozhiqi14** [comment]
I had the same empty embedding error
