### ISSUE TITLE
model.load() is stuck

### ISSUE THREAD

**Issue by parmeshashwath** [epfml/sent2vec#69]
When trying to the load the **torontobooks_unigrams.bin**   the process is stuck and the loading is not getting completed from a long time. Is there any other config that needs to be done before loading.
Code Snippet Used 

import sent2vec
model = sent2vec.Sent2vecModel()
model.load_model(torontobooks_unigrams.bin')

**Comment by mpagli** [comment]
which OS are you on?

**Comment by parmeshashwath** [comment]
OS: Red Hat Enterprise Linux Server release 7.4 (Maipo)
Below is the available memory in GB
              total        used        free      shared  buff/cache   available
Mem:            377          31          10           3         335         336
Swap:            31           0          31

**Comment by mpagli** [comment]
Did you try to use the shared memory parameter? `model.load_model('model.bin', inference_mode=True)`

**Comment by parmeshashwath** [comment]
Yes , Tried with Shared memory parameter as well. But still no luck. The
machine has a good amount of memory, not sure what is the issue here


Regards,
Parmesh A
+91 9731354958

**Comment by mpagli** [comment]
Ok, I found the reason, will fix soon

**Comment by parmeshashwath** [comment]
Great Thanks for the update. Please let me know once you fix it. Thanks again

**Comment by mpagli** [comment]
Can you pull the latest code and try again?

**Comment by parmeshashwath** [comment]
Yes tried and it's still the same :(. Model is not loading. any other workarounds?

**Comment by mpagli** [comment]
You did 'pip install .  --upgrade'?

**Comment by parmeshashwath** [comment]
Thanks this worked. Able to get the sentence embeddings.
