### ISSUE TITLE
nnSent segfault?

### ISSUE THREAD

**Issue by Gldkslfmsd** [epfml/sent2vec#7]
I'm still getting this segfault. My machine seems to have lots of free memory and I have no idea what's happening. Any help?

```
$ ./fasttext nnSent torontobooks_unigrams.bin 1 < sentence
Pre-computing sentence vectors... done.
Segmentation fault (core dumped)
```

**Comment by martinjaggi** [comment]
did you try `./fasttext nnSent torontobooks_unigrams.bin some_sentences.txt` ?

**Comment by Gldkslfmsd** [comment]
I've tried it right now. It doesn't segfault anymore but I can't see any meaningful output...

I followed the usage message, it seems to be obsolete:

```
$ ./fasttext nnSent
usage: fasttext nn <model> <k>

  <model>      model filename
  <k>          (optional; 10 by default) predict top k labels
```

**Comment by martinjaggi** [comment]
if you want sentences (`nnSent`) not words (`nn`), then a list of candidate sentences is mandatory after the model argument

**Comment by Gldkslfmsd** [comment]
Then the help message is wrong. Can you update it, please?
And where is the output printed?

**Comment by Gldkslfmsd** [comment]
Is  the "list of candidate sentences" file supposed to have some special format or is it just one tokenized sentence per file?

**Comment by martinjaggi** [comment]
tokenized sentence per line
