### ISSUE TITLE
How to install sent2vec?

### ISSUE THREAD

**Issue by rv-ltran** [epfml/sent2vec#76]
I want to use sent2vec on mac

I am following the following codes and ran into the error: "no module named 'sent2vec'". Do you know how to resolve this?

import sent2vec
model = sent2vec.Sent2vecModel()
model.load_model('model.bin')
emb = model.embed_sentence("once upon a time .")

I have done the following steps, and fastText-0.9.1 has been installed successfully

$ wget https://github.com/facebookresearch/fastText/archive/v0.9.1.zip
$ unzip v0.9.1.zip
$ cd fastText-0.9.1
$ make
$pip install .

**Comment by AlexanderDavid** [comment]
Did you clone this repository and run `pip install .` inside it? It seems like you just installed FastText.

**Comment by OnlyBelter** [comment]
After installing fasttext and sent2vec, how to use `sent2vec` as a commond line?

Such as the demo code shows:
`./fasttext sent2vec -input wiki_sentences.txt -output my_model -minCount 8 -dim 700 -epoch 9 -lr 0.2 -wordNgrams 2 -loss ns -neg 10 -thread 20 -t 0.000005 -dropoutK 4 -minCountLabel 20 -bucket 4000000 -maxVocabSize 750000 -numCheckPoints 10`

**Comment by 1eclipse** [comment]
My OS is win10.  Did someone install it successfully？I have some questions in detail. Can you give me some help? thanks!!!

**Comment by martinjaggi** [comment]
closing this, thanks alex for the help!
