### ISSUE TITLE
Training model with L1 regularization

### ISSUE THREAD

**Issue by patrickfrank1** [epfml/sent2vec#77]
Hi,

in your 2018 paper you also train models on a modified loss function that includes L1 regularization. How can I train a new model with L1 regularization? Is this functionality also implemented in this library here?

Cheers, Patrick

**Comment by mpagli** [comment]
Not sure if this was pushed in the final repo. Any idea @guptaprkhr ?

**Comment by guptaprkhr** [comment]
Hello, the functionality was not added in the repo as it gave only marginal gains.
