### ISSUE TITLE
about loss

### ISSUE THREAD

**Issue by 3NFBAGDU** [epfml/sent2vec#89]
What is the acceptable loss for sent2vec after training?

**Comment by enviz** [comment]
not sure but here's a good source that explains all the loss functions that they have used: 
https://www.cis.uni-muenchen.de/esslli2017/pdf/print,embedgd.pdf

**Comment by martinjaggi** [comment]
thanks, this is a good reference. the question is the same for word2vec and senct2vec.  it's hard to say which loss level would ensure good quality, as it depends on many unknowns and other factors of the training corpus. closing this now
