### ISSUE TITLE
nnSent return empty

### ISSUE THREAD

**Issue by Avi197** [epfml/sent2vec#93]
`./fasttext nnSent torontobooks_unigrams.bin text.txt [3]`
`Number of sentences in the corpus file is 11.`
`Pre-computing sentence vectors... done`
`Query sentence?`
`some random text`
` `
`Query sentences?`

I try query the sentence with the torontobooks_unigrams.bin and a text file with some random sentences as corpus, but it return nothing

**Comment by mpagli** [comment]
weird, what you could do is to implement yourself your NN using the python wrapper and numpy.

**Comment by guptaprkhr** [comment]
Closing the issue due to lack of activity
