### ISSUE TITLE
nnsent returns similarity above 1

### ISSUE THREAD

**Issue by tqx94** [epfml/sent2vec#94]
Hi, I ran the nnsent commands, and there were instances where I got results above 1. 

Does that means the embeddings for sent2vec are not normalised?

Thanks, 
Farren

**Comment by mpagli** [comment]
Indeed they are not normalized.

**Comment by tqx94** [comment]
Hi, thanks for getting back! do you have suggestions on how I could normalise the cosine similarity? 
I’m not very familiar with this.
