### ISSUE TITLE
Process dies on load_model when model file is not found!

### ISSUE THREAD

**Issue by 0x01h** [epfml/sent2vec#95]
Hi,

```python
model = sent2vec.Sent2vecModel()
model.load_model('sexy_results.bin')
```

The code above kills the **Python** process without throwing error like `FileNotFound`, if model file not exists in the underlying directory. Could you please handle these kind of cases?

Thank you!

**Comment by guptaprkhr** [comment]
Hello, 
We are looking into it and will add a error code in the next major update.
