### ISSUE TITLE
Sent2vec hangs at 100% upon training and do not output anything

### ISSUE THREAD

**Issue by tqx94** [epfml/sent2vec#97]
HI, I have trained a sent2vec model up till 100% for a week. However, there is no error message and there is no output from sent2vec as shown below:
![image](https://user-images.githubusercontent.com/19548371/68355539-893e7180-014a-11ea-846a-728563c90e60.png)

 Could you kindly assist with this matter?

Below is how my top CPU and memory usage looks like:
![image](https://user-images.githubusercontent.com/19548371/68355516-79bf2880-014a-11ea-9891-c4aa07a1a193.png)

**Comment by guptaprkhr** [comment]
Hello, did you try reproducing the issue? I believe that it might be a one-off case.
